# Site settings
name: Mohit Kumar
title: Mohit Kumar | Front End Web and Python Developer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://mohitkum4r.github.io/
baseurl: ''
email: mohitkumar4706@gmail.com
cover: https://mohitkum4r.github.io/img/og.png
logo: https://mohitkum4r.github.io/img/emojis/technologist.png
resume: https://mohitkum4r.github.io/resume.pdf
social:
  - title: email
    url: mailto:mohitkumar4706@gmail.com
  - title: linkedin
    url: https://www.linkedin.com/in/mohitkum4r/
  - title: twitter
    url: https://twitter.com/mohitkum4r
  - title: instagram
    url: https://instagram.com/mohitkum4r
  # - title: codepen
  #   url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/mohitkum4r
  # - title: linkedin
  #   url: https://www.linkedin.com/in/bchiang7

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
