# Site settings
name: Mohit Kumar
title: Mohit Kumar | Backend Software Developer
description: Design-minded backend software developer.
url: https://mohitkum4r.github.io/
baseurl: ''
email: mo.kum4r@gmail.com
cover: https://mohitkum4r.github.io/img/cover.PNG
logo: https://mohitkum4r.github.io/img/emojis/technologist.png
resume: https://mohitkum4r.github.io/Mohit_Kumar_Resume.pdf
social:
  - title: email
    url: mailto:mo.kum4r@gmail.com
  - title: linkedin
    url: https://www.linkedin.com/in/mohitkum4r/
  - title: x
    url: https://x.com/mohitkum4r
  - title: instagram
    url: https://instagram.com/mohitkum4r
  - title: github
    url: https://github.com/mohitkum4r

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
